# Generated by Django 4.1.5 on 2023-02-02 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Views_count',
            new_name='views_count',
        ),
    ]
